site_name: Yggdrasil API
site_url: https://oen44.github.io/yggdrasil

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Prefabs: prefabs.md
  - Using trees in-game: usage.md
  - Saving and Loading: serialization.md
  - API Reference:
      - Shared:
          - Yggdrasil: api/shared/yggdrasil.md
          - YggdrasilBaseService: api/shared/yggdrasil-base-service.md
          - YggdrasilAllocationService: api/shared/yggdrasil-allocation-service.md
          - YggdrasilBuilder: api/shared/yggdrasil-builder.md
          - YggdrasilCamera: api/shared/yggdrasil-camera.md
          - YggdrasilConnection: api/shared/yggdrasil-connection.md
          - YggdrasilConnectionsService: api/shared/yggdrasil-connections-service.md
          - YggdrasilDecorationsService: api/shared/yggdrasil-decorations-service.md
          - YggdrasilLineData: api/shared/yggdrasil-line-data.md
          - YggdrasilLoader: api/shared/yggdrasil-loader.md
          - YggdrasilNodeButton: api/shared/yggdrasil-node-button.md
          - YggdrasilNodesService: api/shared/yggdrasil-nodes-service.md
          - YggdrasilPrefabsService: api/shared/yggdrasil-prefabs-service.md
          - YggdrasilTooltip: api/shared/yggdrasil-tooltip.md
          - YggdrasilTreeView: api/shared/yggdrasil-tree-view.md
      - Runtime:
          - YggdrasilSerializer: api/runtime/yggdrasil-serializer.md
      - Resources:
          - YggdrasilRegistry: api/resources/yggdrasil-registry.md
          - YggdrasilGroup: api/resources/yggdrasil-group.md
          - YggdrasilTree: api/resources/yggdrasil-tree.md
          - YggdrasilTreeState: api/resources/yggdrasil-tree-state.md
          - YggdrasilConnection: api/resources/yggdrasil-connection.md
          - YggdrasilNode: api/resources/yggdrasil-node.md
          - YggdrasilPrefab: api/resources/yggdrasil-prefab.md
          - YggdrasilAttribute: api/resources/yggdrasil-attribute.md

theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences